### ISSUE TITLE
Missing .dlls

### ISSUE THREAD

**Issue by dbechrd** [radareorg/iaito#62]
## Environment Details

The Win64 release is missing 4 .dlls. I downloaded the latest radare2 and tried to copy paste, but iaito depends on older versions of them. Please just include all of the relevant .dlls for iaito to run in the release package. I shouldn't have to install them into my system directory, and that won't even work if I'm using a newer version of the dependency.

**Comment by trufae** [comment]
Yep! im aware of this, the QT libs should be shipped with all the release builds i think, because we can't rely on users to have the right version and seems like there are abi changes and multiple distributors of the libs.

Canyou name those 4 missing libs? just in case its msising something else?
thank you

**Comment by dbechrd** [comment]
I deleted all of the relevant stuff to test this since it didn't work. If you download the latest release on any Windows machine that doesn't have the .dlls you should be able to diagnose.

**Comment by huornlmj** [comment]
r_core.dll
r_cons.dll
r_config.dll
r_io.dll

**Comment by trufae** [comment]
Those libs are intended to be missing because they are provided by r2. Pick theast release and drop the libs from the zip in there

**Comment by AltoRetrato** [comment]
I noticed the [iaito releases](https://github.com/radareorg/iaito/releases) since 5.7.8 contain only the source code, without binaries.

But I also noticed that even though [iaito-5.7.6-w64.zip](https://github.com/radareorg/iaito/releases/download/5.7.6/iaito-5.7.6-w64.zip) has the .exe, it is missing the QT DLLs. When I run `iaito.exe` in the same folder with `radare2.exe` (from [radare2-5.7.6-w64.zip](https://github.com/radareorg/radare2/releases/download/5.7.6/radare2-5.7.6-w64.zip)), it complaints about these missing files:

- `Qt5Cored.dll`
- `Qt5Guid.dll`
- `Qt5Widgetsd.dll`
- `Qt5Svgd.dll`
